#server
server.port: 5005
#server.address: wifi_address

#mongodb
spring.data.mongodb:
  uri:
  database: event
#spring mail
spring.mail:
  host: smtp.gmail.com
  port: 587
  username:
  password:
  properties.mail.smtp:
    auth: true
    connectiontimeout: 5000
    timeout: 5000
    writetimeout: 5000
    starttls.enable: true

#logging
logging.level.org.springframework.data: debug
#logging.level.root: trace
FRONT_URL: "http://localhost:5000/"